### ISSUE TITLE
Không thể đóng được zoom image khi chatter ở chế độ bên cạnh

### ISSUE THREAD

**Issue by davidtranhp** [tvtma/backend_theme#5]
Khi hover đến icon `x` để đóng thì bị vùng thông tin user che đè lên
https://drive.google.com/file/d/1bwYYwDrS9Z6M3uqAAQfr28g6LVmCSIQe/view

**Comment by leotranviindoo** [comment]
Đúng rồi anh, em đang định tạo issue cho vụ này
